/**
 * composio-catalog.ts — Local cache of the Composio tool catalogue.
 *
 * The catalogue is generated by `scripts/sync-composio-catalog.mjs` and stored
 * under `generated/composio-catalog/<apiVersion>/<toolkit>.json`. Each toolkit
 * file contains the full tool records (schemas, tags, version, etc.) for every
 * non-deprecated, latest-version tool in that toolkit.
 *
 * Runtime code loads only the toolkit files it needs, converts the raw Composio
 * records into our `ToolContract` shape, and caches them with a short TTL.
 */

import { access, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { ConnectorActionRisk } from "../loop-engine/spec-contracts.js";
import { connectorActionToolRef } from "../tool-spec/tool-contracts.js";
import type { ToolContract } from "../tool-spec/types.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CATALOG_ROOT = path.resolve(__dirname, "..", "..", "..", "generated", "composio-catalog");
const DEFAULT_API_VERSION = "v3.1";
const DEFAULT_TTL_MS = 5 * 60 * 1000;
const MAX_CACHED_TOOLKITS = 50;

export type ComposioCatalogTool = {
  slug: string;
  name: string;
  description: string;
  human_description?: string;
  toolkit: { slug: string; name: string; logo?: string };
  input_parameters: Record<string, unknown>;
  output_parameters: Record<string, unknown>;
  no_auth: boolean;
  available_versions: string[];
  version: string;
  scopes: string[];
  scope_requirements: unknown;
  tags: string[];
  is_deprecated: boolean;
};

export type ComposioCatalogManifest = {
  apiVersion: string;
  apiBaseUrl: string;
  fetchedAt: string;
  totalToolsFetched: number;
  catalogTools: number;
  toolkits: number;
  toolkitList: string[];
};

export type ComposioCatalogSearchResult = {
  tool: ComposioCatalogTool;
  score: number;
};

export type ComposioToolIndexEntry = {
  slug: string;
  toolkit: string;
  name: string;
  description: string;
  humanDescription: string | null;
  tags: string[];
  risk: string;
  noAuth: boolean;
};

export class ComposioCatalogNotFoundError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ComposioCatalogNotFoundError";
  }
}

function getCatalogBasePath(apiVersion = DEFAULT_API_VERSION): string {
  return path.join(CATALOG_ROOT, apiVersion);
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function normalizeToolkit(value: string): string {
  return value.trim().toLowerCase();
}

function normalizeSlug(value: string): string {
  return value.trim().toUpperCase();
}

function inferRisk(tool: ComposioCatalogTool): ConnectorActionRisk {
  const tags = tool.tags.map((tag) => tag.toLowerCase());
  const description = `${tool.description} ${tool.human_description ?? ""}`.toLowerCase();
  const slug = tool.slug.toLowerCase();

  if (tags.includes("destructive") || /delete|remove|permanent|erase|destroy/.test(slug)) {
    return "destructive";
  }
  if (tags.includes("send") || /send|post|broadcast|notify|dispatch|deliver/.test(slug)) {
    return "send";
  }
  if (tags.includes("write") || tags.includes("create") || tags.includes("update") || /create|update|edit|write|add|insert/.test(slug)) {
    return "write";
  }
  if (tags.includes("read") || tags.includes("list") || tags.includes("get") || /get|list|search|fetch|read|find/.test(slug)) {
    return "read";
  }
  return "write";
}

function schemaFromParameters(params: Record<string, unknown>): Record<string, unknown> {
  if (!params || typeof params !== "object" || Array.isArray(params)) {
    return { type: "object", properties: {} };
  }
  return params as Record<string, unknown>;
}

export function convertCatalogToolToContract(tool: ComposioCatalogTool): ToolContract {
  const toolkit = normalizeToolkit(tool.toolkit.slug);
  const actionSlug = normalizeSlug(tool.slug);
  const risk = inferRisk(tool);
  const effect = risk === "read" ? "read_external" : risk === "destructive" ? "irreversible_external" : "write_external";
  const executionMode = effect === "read_external" ? "short_circuit" : "approval_executed";
  const toolRef = connectorActionToolRef({ toolkit, actionSlug });

  return {
    toolRef,
    provider: "composio",
    name: tool.name.trim() || actionSlug,
    description: (tool.human_description ?? tool.description ?? "").trim() || `Composio action ${actionSlug}`,
    skillTags: inferSkillTags(tool),
    effect,
    resources: [toolkit],
    inputSchema: schemaFromParameters(tool.input_parameters),
    outputSchema: schemaFromParameters(tool.output_parameters),
    executionMode,
    approval: {
      required: effect !== "read_external",
      ...(effect !== "read_external"
        ? {
          suggestedGate: { type: "approval" as const, approval: { surface: "confirm.send" } },
          reason: "External side-effect requires operator approval.",
        }
        : {}),
    },
    renderRecommendations: [],
    constraints: {
      toolkit,
      actionSlug,
      risk,
      toolkitVersion: tool.version,
      noAuth: tool.no_auth === true,
      scopes: tool.scopes,
      tags: tool.tags,
    },
    source: "composio_sdk",
  };
}

function inferSkillTags(tool: ComposioCatalogTool): Array<"search" | "retrieve" | "draft" | "summarize" | "transform" | "send" | "create" | "update" | "delete" | "schedule" | "notify" | "analyze"> {
  const tags = new Set<string>();
  const text = `${tool.name} ${tool.description} ${tool.human_description ?? ""} ${tool.tags.join(" ")}`.toLowerCase();
  const slug = tool.slug.toLowerCase();

  if (/search|find|lookup|query/.test(text)) tags.add("search");
  if (/get|list|fetch|retrieve|read/.test(text) || slug.startsWith("get_") || slug.startsWith("list_")) tags.add("retrieve");
  if (/draft|compose|write|generate/.test(text)) tags.add("draft");
  if (/summarize|summary/.test(text)) tags.add("summarize");
  if (/transform|convert|parse|format/.test(text)) tags.add("transform");
  if (/send|post|deliver|dispatch|broadcast/.test(text)) tags.add("send");
  if (/create|add|new|insert/.test(text)) tags.add("create");
  if (/update|edit|modify|patch/.test(text)) tags.add("update");
  if (/delete|remove|destroy|erase/.test(text)) tags.add("delete");
  if (/schedule|calendar|reminder/.test(text)) tags.add("schedule");
  if (/notify|alert|mention|message/.test(text)) tags.add("notify");
  if (/analyze|analysis|metric|report/.test(text)) tags.add("analyze");

  return [...tags] as Array<"search" | "retrieve" | "draft" | "summarize" | "transform" | "send" | "create" | "update" | "delete" | "schedule" | "notify" | "analyze">;
}

class ToolkitCache {
  private cache = new Map<string, { tools: ComposioCatalogTool[]; fetchedAt: number }>();
  private accessOrder: string[] = [];

  constructor(private maxSize: number, private ttlMs: number) {}

  get(toolkit: string): ComposioCatalogTool[] | undefined {
    const entry = this.cache.get(toolkit);
    if (!entry) return undefined;
    if (Date.now() - entry.fetchedAt > this.ttlMs) {
      this.delete(toolkit);
      return undefined;
    }
    this.touch(toolkit);
    return entry.tools;
  }

  set(toolkit: string, tools: ComposioCatalogTool[]): void {
    if (this.cache.has(toolkit)) {
      this.cache.set(toolkit, { tools, fetchedAt: Date.now() });
      this.touch(toolkit);
      return;
    }
    if (this.cache.size >= this.maxSize && this.accessOrder.length > 0) {
      const oldest = this.accessOrder.shift()!;
      this.cache.delete(oldest);
    }
    this.cache.set(toolkit, { tools, fetchedAt: Date.now() });
    this.accessOrder.push(toolkit);
  }

  private touch(toolkit: string): void {
    const idx = this.accessOrder.indexOf(toolkit);
    if (idx >= 0) this.accessOrder.splice(idx, 1);
    this.accessOrder.push(toolkit);
  }

  private delete(toolkit: string): void {
    this.cache.delete(toolkit);
    const idx = this.accessOrder.indexOf(toolkit);
    if (idx >= 0) this.accessOrder.splice(idx, 1);
  }

  clear(): void {
    this.cache.clear();
    this.accessOrder.length = 0;
  }
}

const toolkitCache = new ToolkitCache(MAX_CACHED_TOOLKITS, DEFAULT_TTL_MS);
let manifestPromise: Promise<ComposioCatalogManifest> | null = null;

export async function loadCatalogManifest(apiVersion = DEFAULT_API_VERSION): Promise<ComposioCatalogManifest> {
  const basePath = getCatalogBasePath(apiVersion);
  const manifestPath = path.join(basePath, "manifest.json");
  if (!(await fileExists(manifestPath))) {
    throw new ComposioCatalogNotFoundError(`Composio catalog manifest not found at ${manifestPath}. Run: node scripts/sync-composio-catalog.mjs`);
  }
  const text = await readFile(manifestPath, "utf-8");
  return JSON.parse(text) as ComposioCatalogManifest;
}

let toolsIndexPromise: Promise<ComposioToolIndexEntry[]> | null = null;
let toolsIndexTimestamp = 0;
const TOOLS_INDEX_TTL_MS = 5 * 60 * 1000; // 5 minutes

export async function loadToolsIndex(apiVersion = DEFAULT_API_VERSION): Promise<ComposioToolIndexEntry[]> {
  if (toolsIndexPromise && Date.now() - toolsIndexTimestamp < TOOLS_INDEX_TTL_MS) {
    return toolsIndexPromise;
  }
  const basePath = getCatalogBasePath(apiVersion);
  const indexPath = path.join(basePath, "tools-index.json");
  if (!(await fileExists(indexPath))) {
    throw new ComposioCatalogNotFoundError(`Composio tools index not found at ${indexPath}. Run: npm run sync:composio-catalog`);
  }
  toolsIndexTimestamp = Date.now();
  toolsIndexPromise = readFile(indexPath, "utf-8").then((text) =>
    JSON.parse(text) as ComposioToolIndexEntry[]
  );
  return toolsIndexPromise;
}

export async function searchToolsIndex(input: {
  query: string;
  toolkits?: string[];
  limit?: number;
  apiVersion?: string;
}): Promise<ComposioToolIndexEntry[]> {
  const { query, toolkits, limit = 12, apiVersion = DEFAULT_API_VERSION } = input;
  const terms = query
    .toLowerCase()
    .split(/\s+/)
    .filter((term) => term.length > 2);
  if (terms.length === 0) return [];

  const index = await loadToolsIndex(apiVersion);
  const toolkitSet = toolkits && toolkits.length > 0
    ? new Set(toolkits.map(normalizeToolkit))
    : null;

  const scored = index
    .filter((entry) => (toolkitSet ? toolkitSet.has(entry.toolkit) : true))
    .map((entry) => {
      const haystack = `${entry.slug} ${entry.name} ${entry.description} ${entry.humanDescription ?? ""} ${entry.tags.join(" ")}`.toLowerCase();
      const score = terms.filter((term) => haystack.includes(term)).length;
      return { entry, score };
    })
    .filter((item) => item.score > 0);

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((item) => item.entry);
}

export async function loadToolkitTools(toolkit: string, apiVersion = DEFAULT_API_VERSION): Promise<ComposioCatalogTool[]> {
  const normalizedToolkit = normalizeToolkit(toolkit);
  const cached = toolkitCache.get(normalizedToolkit);
  if (cached) return cached;

  const basePath = getCatalogBasePath(apiVersion);
  const filePath = path.join(basePath, `${normalizedToolkit}.json`);
  if (!(await fileExists(filePath))) {
    return [];
  }

  const text = await readFile(filePath, "utf-8");
  const data = JSON.parse(text) as { toolkit: string; tools: ComposioCatalogTool[] };
  const tools = Array.isArray(data.tools) ? data.tools : [];
  toolkitCache.set(normalizedToolkit, tools);
  return tools;
}

export async function getCatalogTool(toolkit: string, slug: string, apiVersion = DEFAULT_API_VERSION): Promise<ComposioCatalogTool | null> {
  const tools = await loadToolkitTools(toolkit, apiVersion);
  const normalizedSlug = normalizeSlug(slug);
  return tools.find((tool) => normalizeSlug(tool.slug) === normalizedSlug) ?? null;
}

export async function searchCatalog(input: {
  query: string;
  toolkits?: string[];
  limit?: number;
  apiVersion?: string;
}): Promise<ComposioCatalogSearchResult[]> {
  const { query, toolkits, limit = 12, apiVersion = DEFAULT_API_VERSION } = input;
  const terms = query
    .toLowerCase()
    .split(/\s+/)
    .filter((term) => term.length > 2);
  if (terms.length === 0) return [];

  const manifest = await loadCatalogManifest(apiVersion);
  const toolkitList = toolkits && toolkits.length > 0
    ? toolkits.map(normalizeToolkit).filter((t) => manifest.toolkitList.includes(t))
    : manifest.toolkitList;

  const results: ComposioCatalogSearchResult[] = [];
  for (const toolkit of toolkitList) {
    const tools = await loadToolkitTools(toolkit, apiVersion);
    for (const tool of tools) {
      const haystack = `${tool.slug} ${tool.name} ${tool.description} ${tool.human_description ?? ""} ${tool.tags.join(" ")}`.toLowerCase();
      const matches = terms.filter((term) => haystack.includes(term)).length;
      if (matches === 0) continue;
      results.push({ tool, score: matches });
    }
  }

  results.sort((a, b) => b.score - a.score);
  return results.slice(0, limit);
}

export async function getCatalogContracts(input: {
  toolkits?: string[];
  slugs?: string[];
  apiVersion?: string;
}): Promise<ToolContract[]> {
  const { toolkits, slugs, apiVersion = DEFAULT_API_VERSION } = input;

  let targetToolkits: string[] | undefined = toolkits?.map(normalizeToolkit);

  // When specific slugs are requested but toolkits are not provided, use the
  // lightweight index to avoid iterating every toolkit file.
  if (slugs && slugs.length > 0 && !targetToolkits) {
    const index = await loadToolsIndex(apiVersion);
    const slugSet = new Set(slugs.map(normalizeSlug));
    const toolkitForSlug = new Map<string, string>();
    for (const entry of index) {
      if (slugSet.has(normalizeSlug(entry.slug))) {
        toolkitForSlug.set(normalizeSlug(entry.slug), entry.toolkit);
      }
    }
    targetToolkits = [...new Set(toolkitForSlug.values())];
  }

  const manifest = await loadCatalogManifest(apiVersion);
  const toolkitList = targetToolkits
    ? targetToolkits.filter((t) => manifest.toolkitList.includes(t))
    : manifest.toolkitList;

  const slugSet = slugs && slugs.length > 0 ? new Set(slugs.map(normalizeSlug)) : null;
  const contracts: ToolContract[] = [];

  for (const toolkit of toolkitList) {
    const tools = await loadToolkitTools(toolkit, apiVersion);
    for (const tool of tools) {
      if (slugSet && !slugSet.has(normalizeSlug(tool.slug))) continue;
      contracts.push(convertCatalogToolToContract(tool));
    }
  }

  return contracts;
}

export function clearCatalogCache(): void {
  manifestPromise = null;
  toolkitCache.clear();
}
