services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tallei
      POSTGRES_PASSWORD: tallei
      POSTGRES_DB: tallei
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
