const fs = require('fs');
const file = 'dashboard/app/dashboard/documents/page.tsx';
let content = fs.readFileSync(file, 'utf8');

const replacements = [
  ['style={{ display: "flex", flexDirection: "column", gap: "1rem", maxWidth: 980, margin: "0 auto", paddingBottom: "3rem" }}', 'className="flex flex-col gap-4 max-w-[980px] mx-auto pb-12"'],
  ['style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "0.75rem", flexWrap: "wrap" }}', 'className="flex items-center justify-between gap-3 flex-wrap"'],
  ['style={{ margin: 0, fontSize: "1.5rem", fontWeight: 700, color: "var(--text)" }}', 'className="m-0 text-2xl font-bold text-slate-900 dark:text-slate-100"'],
  ['style={{ margin: "0.25rem 0 0", color: "var(--text-muted)", fontSize: "0.9rem" }}', 'className="mt-1 text-sm text-slate-500 dark:text-slate-400"'],
  [`          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "0.45rem",
            padding: "0.5rem 0.8rem",
            background: "var(--surface)",
            border: "1px solid var(--border)",
            borderRadius: "var(--radius-md)",
            color: "var(--text-2)",
            cursor: refreshing || loading ? "wait" : "pointer",
          }}`, `          className="inline-flex items-center gap-2 px-3 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-md text-slate-700 dark:text-slate-300 disabled:cursor-wait hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors"`],
  ['style={{ background: "#fef2f2", border: "1px solid #fecaca", borderRadius: "var(--radius-md)", padding: "0.75rem 0.9rem", color: "#991b1b", fontSize: "0.88rem" }}', 'className="bg-red-50 border border-red-200 rounded-md py-3 px-4 text-red-800 text-sm"'],
  ['style={{ boxShadow: "var(--shadow-sm)" }}', 'className="shadow-sm"'],
  ['style={{ color: "var(--text-muted)" }}', 'className="text-slate-500"'],
  ['style={{ marginTop: "0.85rem" }}', 'className="mt-3"'],
  ['style={{ display: "flex", flexDirection: "column", gap: "0.6rem" }}', 'className="flex flex-col gap-2"'],
  ['style={{ height: 64, width: "100%", borderRadius: "var(--radius-md)", border: "1px solid var(--border-light)", background: "var(--surface)" }}', 'className="h-16 w-full rounded-md border border-slate-200 bg-white dark:bg-slate-900 dark:border-slate-800 animate-pulse"'],
  [`        <div style={{
          border: "1px solid var(--border-light)",
          borderRadius: "var(--radius-lg)",
          background: "var(--surface)",
          padding: "2rem 1rem",
          textAlign: "center",
          color: "var(--text-muted)",
        }}>`, `        <div className="border border-slate-200 dark:border-slate-800 rounded-lg bg-white dark:bg-slate-900 p-8 text-center text-slate-500 dark:text-slate-400">`],
  [`          <section style={{
            background: "var(--surface)",
            border: "1px solid var(--border)",
            borderRadius: "var(--radius-lg)",
            overflow: "hidden",
          }}>`, `          <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg overflow-hidden">`],
  ['style={{ padding: "0.85rem 1rem", borderBottom: "1px solid var(--border-light)", fontWeight: 600, color: "var(--text)" }}', 'className="px-4 py-3 border-b border-slate-200 dark:border-slate-800 font-semibold text-slate-900 dark:text-slate-100"'],
  ['style={{ maxHeight: 420, overflowX: "auto", overflowY: "auto" }}', 'className="max-h-[420px] overflow-auto"'],
  ['style={{ width: "100%", borderCollapse: "collapse", minWidth: 760 }}', 'className="w-full border-collapse min-w-[760px]"'],
  ['style={{ background: "#fafafa", borderBottom: "1px solid var(--border-light)" }}', 'className="bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800"'],
  ['style={{ textAlign: "left", padding: "0.65rem 0.85rem", fontSize: "0.78rem", color: "var(--text-muted)" }}', 'className="text-left px-3 py-2.5 text-xs text-slate-500 dark:text-slate-400"'],
  ['style={{ padding: "0.9rem", textAlign: "center", color: "var(--text-muted)", fontSize: "0.84rem" }}', 'className="p-4 text-center text-slate-500 dark:text-slate-400 text-sm"'],
  ['style={{ borderBottom: "1px solid var(--border-light)" }}', 'className="border-b border-slate-200 dark:border-slate-800"'],
  ['style={{ padding: "0.7rem 0.85rem" }}', 'className="px-3 py-2.5"'],
  ['style={{ display: "flex", alignItems: "center", gap: "0.45rem" }}', 'className="flex items-center gap-2"'],
  [`                              style={{
                                border: "none",
                                background: "transparent",
                                color: "var(--text)",
                                cursor: "pointer",
                                fontFamily: "monospace",
                                fontSize: "0.8rem",
                                padding: 0,
                                textAlign: "left",
                              }}`, `                              className="border-none bg-transparent text-slate-900 dark:text-slate-100 cursor-pointer font-mono text-xs p-0 text-left hover:underline"`],
  ['style={{ border: "none", background: "transparent", color: "var(--text-muted)", cursor: "pointer", padding: 0 }}', 'className="border-none bg-transparent text-slate-500 dark:text-slate-400 cursor-pointer p-0 hover:text-slate-700 dark:hover:text-slate-300"'],
  ['style={{ padding: "0.7rem 0.85rem", color: "var(--text-2)", fontSize: "0.86rem" }}', 'className="px-3 py-2.5 text-slate-700 dark:text-slate-300 text-sm"'],
  ['style={{ display: "flex", flexDirection: "column", gap: "0.2rem" }}', 'className="flex flex-col gap-1"'],
  ['style={{ color: "var(--text-muted)", fontSize: "0.75rem", lineHeight: 1.35 }}', 'className="text-slate-500 dark:text-slate-400 text-xs leading-relaxed"'],
  ['style={{ fontSize: "0.75rem", color: "#2563eb", textDecoration: "none" }}', 'className="text-xs text-blue-600 dark:text-blue-400 hover:underline"'],
  ['style={{ padding: "0.7rem 0.85rem", color: "var(--text-muted)", fontSize: "0.82rem", fontFamily: "monospace" }}', 'className="px-3 py-2.5 text-slate-500 dark:text-slate-400 text-xs font-mono"'],
  ['style={{ padding: "0.7rem 0.85rem", color: "var(--text-muted)", fontSize: "0.83rem" }}', 'className="px-3 py-2.5 text-slate-500 dark:text-slate-400 text-sm"'],
  [`                          <span style={{
                            display: "inline-flex",
                            fontSize: "0.72rem",
                            fontWeight: 600,
                            borderRadius: "var(--radius-pill)",
                            padding: "0.2rem 0.5rem",
                            background: chip.bg,
                            color: chip.color,
                            border: \`1px solid \${chip.border}\`,
                          }}>`, `                          <span style={{ background: chip.bg, color: chip.color, border: \`1px solid \${chip.border}\` }} className="inline-flex text-[0.72rem] font-semibold rounded-full px-2 py-0.5">`],
  [`            <div style={{
              borderTop: "1px solid var(--border-light)",
              padding: "0.65rem 0.9rem",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: "0.65rem",
              flexWrap: "wrap",
            }}>`, `            <div className="border-t border-slate-200 dark:border-slate-800 px-4 py-3 flex items-center justify-between gap-3 flex-wrap">`],
  ['style={{ color: "var(--text-muted)", fontSize: "0.8rem" }}', 'className="text-slate-500 dark:text-slate-400 text-sm"'],
  ['style={{ display: "inline-flex", alignItems: "center", gap: "0.4rem" }}', 'className="inline-flex items-center gap-2"'],
  [`                  style={{
                    border: "1px solid var(--border)",
                    background: "var(--surface)",
                    color: "var(--text-2)",
                    borderRadius: "var(--radius-sm)",
                    fontSize: "0.78rem",
                    padding: "0.3rem 0.55rem",
                    cursor: docPage === 1 ? "not-allowed" : "pointer",
                    opacity: docPage === 1 ? 0.55 : 1,
                  }}`, `                  className="border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded text-xs px-2.5 py-1.5 disabled:cursor-not-allowed disabled:opacity-50 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"`],
  ['style={{ color: "var(--text-muted)", fontSize: "0.78rem", minWidth: 70, textAlign: "center" }}', 'className="text-slate-500 dark:text-slate-400 text-xs min-w-[70px] text-center"'],
  [`                  style={{
                    border: "1px solid var(--border)",
                    background: "var(--surface)",
                    color: "var(--text-2)",
                    borderRadius: "var(--radius-sm)",
                    fontSize: "0.78rem",
                    padding: "0.3rem 0.55rem",
                    cursor: docPage === docPageCount ? "not-allowed" : "pointer",
                    opacity: docPage === docPageCount ? 0.55 : 1,
                  }}`, `                  className="border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded text-xs px-2.5 py-1.5 disabled:cursor-not-allowed disabled:opacity-50 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"`],
  ['style={{ width: "100%", borderCollapse: "collapse", minWidth: 560 }}', 'className="w-full border-collapse min-w-[560px]"'],
  [`                  style={{
                    border: "1px solid var(--border)",
                    background: "var(--surface)",
                    color: "var(--text-2)",
                    borderRadius: "var(--radius-sm)",
                    fontSize: "0.78rem",
                    padding: "0.3rem 0.55rem",
                    cursor: lotPage === 1 ? "not-allowed" : "pointer",
                    opacity: lotPage === 1 ? 0.55 : 1,
                  }}`, `                  className="border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded text-xs px-2.5 py-1.5 disabled:cursor-not-allowed disabled:opacity-50 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"`],
  [`                  style={{
                    border: "1px solid var(--border)",
                    background: "var(--surface)",
                    color: "var(--text-2)",
                    borderRadius: "var(--radius-sm)",
                    fontSize: "0.78rem",
                    padding: "0.3rem 0.55rem",
                    cursor: lotPage === lotPageCount ? "not-allowed" : "pointer",
                    opacity: lotPage === lotPageCount ? 0.55 : 1,
                  }}`, `                  className="border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded text-xs px-2.5 py-1.5 disabled:cursor-not-allowed disabled:opacity-50 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"`],
  [`          style={{
            position: "fixed",
            inset: 0,
            zIndex: 60,
            background: "rgba(15, 23, 42, 0.48)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "1rem",
          }}`, `          className="fixed inset-0 z-[60] bg-slate-900/50 flex items-center justify-center p-4"`],
  [`            style={{
              width: "min(980px, 100%)",
              maxHeight: "90vh",
              background: "var(--surface)",
              border: "1px solid var(--border)",
              borderRadius: "var(--radius-xl)",
              display: "flex",
              flexDirection: "column",
              overflow: "hidden",
            }}`, `            className="w-[min(980px,100%)] max-h-[90vh] bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl flex flex-col overflow-hidden"`],
  [`            <div style={{
              padding: "0.8rem 1rem",
              borderBottom: "1px solid var(--border-light)",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: "0.8rem",
            }}>`, `            <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between gap-3">`],
  ['style={{ display: "flex", alignItems: "center", gap: "0.5rem", minWidth: 0 }}', 'className="flex items-center gap-2 min-w-0"'],
  ['style={{ color: "var(--text)", fontSize: "0.92rem", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}', 'className="text-slate-900 dark:text-slate-100 text-sm whitespace-nowrap overflow-hidden text-ellipsis"'],
  [`                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      gap: "0.35rem",
                      border: "1px solid #fecaca",
                      background: "#fef2f2",
                      color: "#991b1b",
                      borderRadius: "var(--radius-sm)",
                      fontSize: "0.8rem",
                      padding: "0.35rem 0.55rem",
                      cursor: deleting ? "wait" : "pointer",
                    }}`, `                    className="inline-flex items-center gap-1.5 border border-red-200 bg-red-50 text-red-800 rounded text-xs px-2.5 py-1.5 disabled:cursor-wait hover:bg-red-100 transition-colors"`],
  [`                  style={{
                    border: "1px solid var(--border)",
                    background: "var(--surface)",
                    color: "var(--text-2)",
                    borderRadius: "var(--radius-sm)",
                    fontSize: "0.8rem",
                    padding: "0.35rem 0.55rem",
                    cursor: "pointer",
                  }}`, `                  className="border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded text-xs px-2.5 py-1.5 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"`],
  ['style={{ padding: "0.85rem 1rem", overflow: "auto" }}', 'className="p-4 overflow-auto"'],
  ['style={{ color: "var(--text-muted)", margin: 0 }}', 'className="text-slate-500 dark:text-slate-400 m-0"'],
  ['style={{ display: "flex", alignItems: "center", gap: "0.6rem", marginBottom: "0.75rem", flexWrap: "wrap" }}', 'className="flex items-center gap-2.5 mb-3 flex-wrap"'],
  ['style={{ color: "var(--text-muted)", fontSize: "0.82rem" }}', 'className="text-slate-500 dark:text-slate-400 text-sm"'],
  ['style={{ fontSize: "0.78rem", color: "#2563eb", textDecoration: "none" }}', 'className="text-xs text-blue-600 dark:text-blue-400 hover:underline"'],
  [`                    <span style={{
                      display: "inline-flex",
                      borderRadius: "var(--radius-pill)",
                      padding: "0.2rem 0.5rem",
                      fontSize: "0.72rem",
                      fontWeight: 600,
                      border: \`1px solid \${statusChip(selected.status).border}\`,
                      color: statusChip(selected.status).color,
                      background: statusChip(selected.status).bg,
                    }}>`, `                    <span style={{ background: statusChip(selected.status).bg, color: statusChip(selected.status).color, border: \`1px solid \${statusChip(selected.status).border}\` }} className="inline-flex rounded-full px-2 py-0.5 text-[0.72rem] font-semibold">`],
  [`                  <pre style={{
                    margin: 0,
                    whiteSpace: "pre-wrap",
                    wordBreak: "break-word",
                    fontSize: "0.84rem",
                    lineHeight: 1.5,
                    color: "var(--text-2)",
                    background: "#f8fafc",
                    border: "1px solid var(--border-light)",
                    borderRadius: "var(--radius-md)",
                    padding: "0.85rem",
                  }}>`, `                  <pre className="m-0 whitespace-pre-wrap break-words text-sm leading-relaxed text-slate-700 dark:text-slate-300 bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-800 rounded-md p-4">`],
  ['style={{ display: "flex", flexDirection: "column", gap: "0.85rem" }}', 'className="flex flex-col gap-3.5"'],
  ['style={{ border: "1px solid var(--border-light)", borderRadius: "var(--radius-md)", overflow: "hidden" }}', 'className="border border-slate-200 dark:border-slate-800 rounded-md overflow-hidden"'],
  ['style={{ padding: "0.55rem 0.7rem", borderBottom: "1px solid var(--border-light)", background: "#fafafa", color: "var(--text)", fontSize: "0.82rem", fontFamily: "monospace" }}', 'className="px-3 py-2 border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 text-slate-900 dark:text-slate-100 text-sm font-mono"'],
  ['style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "0.5rem" }}', 'className="flex items-center justify-between gap-2"'],
  ['style={{ fontSize: "0.75rem", color: "#2563eb", textDecoration: "none", fontFamily: "inherit" }}', 'className="text-xs text-blue-600 dark:text-blue-400 hover:underline font-inherit"'],
  ['style={{ margin: 0, padding: "0.7rem", whiteSpace: "pre-wrap", wordBreak: "break-word", fontSize: "0.82rem", color: "var(--text-2)", lineHeight: 1.5 }}', 'className="m-0 p-3 whitespace-pre-wrap break-words text-sm text-slate-700 dark:text-slate-300 leading-relaxed"']
];

for (const [search, replace] of replacements) {
  content = content.split(search).join(replace);
}

fs.writeFileSync(file, content);
